// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { SUPABASE_PROJECT_REF, supabasePublicConfig } from "@/config/supabase-public";
import type { Database } from "./types";

function resolveSupabaseConfig() {
  const envUrl = import.meta.env.VITE_SUPABASE_URL?.trim();
  const envKey = (
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY
  )?.trim();

  const envMatchesProject =
    !!envUrl &&
    !!envKey &&
    envUrl.includes(SUPABASE_PROJECT_REF);

  if (envMatchesProject) {
    return { url: envUrl, key: envKey };
  }

  if (envUrl && !envUrl.includes(SUPABASE_PROJECT_REF)) {
    console.warn(
      `[supabase] Ignoring VITE_SUPABASE_URL for another project (${envUrl}). ` +
        `Using ${supabasePublicConfig.url}. Update or remove old values in Lovable Cloud → Secrets.`
    );
  }

  return {
    url: supabasePublicConfig.url,
    key: supabasePublicConfig.publishableKey,
  };
}

const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = resolveSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
